### ISSUE TITLE
Add console logging of model outputs into a file in a tensor board dir

### ISSUE THREAD

**Issue by kudep** [deeppavlov/DeepPavlov#1070]
Deeppavlov have no file to which model console logs would be written

**Comment by yoptar** [comment]
Suggestion: write `log.jsonl` to the `tensorboard_log_dir` if it's set

**Comment by Kolpnick** [comment]
Hello, @kudep!
In our latest release (version 1.2.0) the requested feature is present. If you think this isn’t present in the new version, let us know.

**Comment by kudep** [comment]
It's present, thank for attention
