### ISSUE TITLE
Documentation for metrics 'ner_f1', 'ner_token_f1'

### ISSUE THREAD

**Issue by PeganovAnton** [deeppavlov/DeepPavlov#1262]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

**What problem are we trying to solve?**:
```
There is no documentation or docstrings for these metrics.
```

**How can we solve it?**:
```
Add information about tags used and supported tagging schemes.
```

**Are there other issues that block this solution?**:
```
No
```

**Comment by IgnatovFedor** [comment]
Fixed in #1655
