### ISSUE TITLE
ERROR in 'deeppavlov.core.common.params'['params'] at line 112

### ISSUE THREAD

**Issue by exelents** [deeppavlov/DeepPavlov#1270]
**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):
Name: deeppavlov
Version: 0.10.0

**Python version**:
Python 3.7.7

**Operating system** (ubuntu linux, windows, ...):
Arch linux

**Issue**:
When i try to run kbqa model I got an error:
https://pastebin.com/20d1YfJr
What's going on and how to overcome it?

**Content or a name of a configuration file**:
```
kbqa_cq
```

**Command that led to error**:
```
python3 deeppavlov/deep.py interact kbqa_cq
```

**Error (including full traceback)**:
```
https://pastebin.com/20d1YfJr
```

**Comment by dmitrijeuseew** [comment]
The component RelRanker requires GPU because the model uses CudnnGRU, this bug will be fixed in the next release (optional usage of CudnnCompatibleGRU or CudnnGRU depending of whether the user uses GPU or not).

**Comment by exelents** [comment]
How much of GPU memory I need to run RelRanker? I have installed tf-gpu and it seems I got memory allocation error. I have only GeForce 940MX  with 2GB of memory.

**Comment by exelents** [comment]
Errors like that:
```
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[512,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node Optimizer/Optimizer/bert/embeddings/position_embeddings/AdamWeightDecayOptimizer/Assign}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

```

**Comment by Kolpnick** [comment]
@exelents, sorry for the late response.
We tested kbqa_cq_en config from the DeepPavlov latest version 1.2.0 and didn’t encounter the described problem. If you are still having difficulties with this, please let us know.
