### ISSUE TITLE
Code to train model from scratch

### ISSUE THREAD

**Issue by VikasRajashekar** [deeppavlov/DeepPavlov#1288]
I am trying to find code for paper: "Sequence Labeling Approach to the Task of
Sentence Boundary Detection". where is it located?

Also, where can find the code to train chatbot model from scratch in a different language?

**Comment by Kolpnick** [comment]
Hi, @VikasRajashekar. Sorry for the late response.
To get the code for the article "Sequence Labeling Approach to the Task of Sentence Boundary Detection", please contact the author of this article. To train a custom chatbot, check out [this](https://github.com/deeppavlov/dream) repo. If you have any other questions, please let us know.
