### ISSUE TITLE
InvalidArgumentError error while building the KBQA model.

### ISSUE THREAD

**Issue by SachinGarg10** [deeppavlov/DeepPavlov#1289]
Hello Team,

I was trying to build the KBQA model using this 'kbqa_cq_online.json' file. But I'm getting this error: 

	InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNNCanonicalToParams' used by node	question_encode/fw_0/cudnn_gru/cudnn_gru/CudnnRNNCanonicalToParams (defined at /home/saga/venvs/kb3.6/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [dropout=0, seed=0, num_params=6, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="gru", seed2=0]
	Registered devices: [CPU, XLA_CPU, XLA_GPU]
	Registered kernels:
	  device='GPU'; T in [DT_DOUBLE]
	  device='GPU'; T in [DT_FLOAT]
	  device='GPU'; T in [DT_HALF]

	 	[[question_encode/fw_0/cudnn_gru/cudnn_gru/CudnnRNNCanonicalToParams]]

Specs:
Ubuntu 16.04, tensorflow-gpu==1.15.0, Cuda version = 10.2

Please let me know, if there is any solution of this. Thank you

**Comment by Kolpnick** [comment]
@SachinGarg10, thank you for your interest!
This config is deprecated. I encourage you to use either kbqa_cq_en or kbqa_cq_ru configs for Knowledge Base Question Answering. You can read more about KBQA in our [docs](http://docs.deeppavlov.ai/en/master/features/models/kbqa.html). If you are still having difficulties with this, please let us know.
