### ISSUE TITLE
wakeword detection module

### ISSUE THREAD

**Issue by raikarsagar** [deeppavlov/DeepPavlov#1300]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

**What problem are we trying to solve?**:
```
Since deeppavlov is a toolkit for custom voicebot building. It makes sense to have a custom wakeword detection module which is similar to ASR. 
```

**How can we solve it?**:
```
At the initial stage, external modules such as https://github.com/Picovoice/porcupine, http://kitt.ai/ can be considered and wrappers can be built around these. Followed by development of custom trainable wakeword detection model.
```

**Are there other issues that block this solution?**:
```
Nothing as of now. We need to check how can asr module be reused for this task. Because, a direct reusage of asr models for wakeword detection would be an overkill.
```

**Comment by danielkornev** [comment]
Sounds quite interesting. Do you use NeMo for ASR?

**Comment by raikarsagar** [comment]
Have used it a bit for demos

**Comment by danielkornev** [comment]
Huh. Do I understand you correctly that you think of contributing a custom wake word detection module to DeepPavlov? :)

**Comment by raikarsagar** [comment]
Firstly wanted to know whether there are any current developments running towards wake word feature?

**Comment by danielkornev** [comment]
Not right now. If you want to contribute yours, we'd be very grateful!
