### ISSUE TITLE
How to include a sentence splitting method into the pipeline of config file ?

### ISSUE THREAD

**Issue by polodealvarado** [deeppavlov/DeepPavlov#1333]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

**What problem are we trying to solve?**:
```
Could it be possible to solve the problem of 512 tokens limit  when we are working with BERT model ?

```

**Possible solution?

```
including a sentence splitting method into the pipeline of the config file

```

**Comment by IgnatovFedor** [comment]
Hey, @polodealvarado! Sorry for the late response.
We changed models input pipeline, so now this is not a problem for the DeepPavlov library. If you are still having difficulties with this, please let us know.
