### ISSUE TITLE
NER model hangs

### ISSUE THREAD

**Issue by max-frai** [deeppavlov/DeepPavlov#1377]
Hello, I run model like this:

`python3 -m deeppavlov riseapi ner_ontonotes_bert_mult -p 5000`

Server has 64gb ram and cpu `i7-8700 CPU @ 3.20GHz`. We send requests to api every 2-3 seconds, it works and responds for 50-200 requests and after this server hangs and only reboot can restore it. The same problem with docker container.

**Comment by IgnatovFedor** [comment]
@max-frai, sorry for the late response!
We tested this issue on DeepPavlov version 1.2.0 and didn’t encounter the described problem. If you are still having difficulties with this, please let us know.
