### ISSUE TITLE
Create Architecture Diagram of DeepPavlov Library

### ISSUE THREAD

**Issue by danielkornev** [deeppavlov/DeepPavlov#1385]

**Comment by danielkornev** [comment]
![image](https://user-images.githubusercontent.com/5264043/107234434-b73cf080-6a34-11eb-8daf-7030d6e88c18.png)

**Comment by danielkornev** [comment]
Decision: apply CJM to Skill Builders concept within the Library

**Comment by rashmiprabhat567** [comment]
Hey @danielkornev , is this issue still need to be modified? If yes, it would be a great help if you discuss it with me. 
Thanks!

> Decision: apply CJM to Skill Builders concept within the Library

**Comment by danielkornev** [comment]
Nope thanks
