### ISSUE TITLE
Finding Cuss Words with NER

### ISSUE THREAD

**Issue by potato-patata** [deeppavlov/DeepPavlov#1403]
**What problem are we trying to solve?**:
```
Training the existing Bert Model to identify cuss words and in future even deal with sarcasm 
```

**How can we solve it?**:
```
By using a semantics of words or using google word2vec and creating vector for identifying and training the model. 
```

**Are there other issues that block this solution?**:
```
Easy to identify cuss words in english, but the same word might mean different thing in other languages. Need to train a model which incorporates this. 
```

**Comment by rashmiprabhat567** [comment]
Hey @potato-patata , would like to work on this issue. Can we do this translation using the googletrans library and then applying the semantics of words for training the model?

**Comment by potato-patata** [comment]
Hey @rashmiprabhat567 we can definitely use it, but we need to find a way to incorporate with dp embeddings. So it is better if we first look into dp embeddings and then proceed.

**Comment by rashmiprabhat567** [comment]
> Hey @rashmiprabhat567 we can definitely use it, but we need to find a way to incorporate with dp embeddings. So it is better if we first look into dp embeddings and then proceed.

got it @potato-patata . I'm looking over to solve this issue. will let you know i I can make any progress

**Comment by rushilpatra** [comment]
hey @potato-patata ! Is this still open to work on?

**Comment by potato-patata** [comment]
Hi, this issue is not for gsoc task. This is just an enhancement suggestion.

**Comment by potato-patata** [comment]
Moreover, I am not the mentor so I apologise if I might have mislead you 😄

**Comment by Kolpnick** [comment]
Hi, @potato-patata. Sorry for the late response!
We already have a [model](https://github.com/deeppavlov/DeepPavlov/blob/master/deeppavlov/configs/classifiers/insults_kaggle_bert.json) that allows to determine toxicity in texts, there is also a [pull request](https://github.com/deeppavlov/DeepPavlov/pull/1651) where a new emotion classifier has been added.
