### ISSUE TITLE
facilities to fine-tune BERT sentence embedder

### ISSUE THREAD

**Issue by vcjob** [deeppavlov/DeepPavlov#1453]
Hello everyone!

I use sentence_multi_cased_L-12_H-768_A-12_pt to extract sentence embeddings. 
I have prepared texts for fine-tuning, but not sure where to start and what to do.
I saw huggingface scripts and train API, but not sure if the deeppavlov model will suit. I also saw legacy script for a regular BERT model finetuning, but I guess this is no go with sentence_multi_cased_L-12_H-768_A-12_pt, or I'm mistaken?
What's the right way to finetune the model? Maybe I better give up on this one and choose another model that can be used for sentence embedding extraction and can be easily finetuned?

Thanks a lot!

**Comment by Kolpnick** [comment]
@vcjob, sorry for the late response.
There is a good [model](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2) for sentence embedding on huggingface that can be fine-tuned. You can also use it in configs from the DeepPavlov library to train that model on your data. If you are still having difficulties with this, let us know!
