### ISSUE TITLE
flutter app for demostration of DeepPavlov features

### ISSUE THREAD

**Issue by ghost** [deeppavlov/DeepPavlov#1507]
Hi @alexeyr ,

Hope you are all well !

I was wondering if you could consider to create a frontend to DeepPavlov based on flutter/dart. It would help to develop use cases.

Cheers,
Luc

**Comment by ayushvrma** [comment]
I would like to work on this. Can you assign me on this issue?

**Comment by danielkornev** [comment]
sure thing, assigned )
