### ISSUE TITLE
Update Docker images, please

### ISSUE THREAD

**Issue by kuraga** [deeppavlov/DeepPavlov#1510]
Good day!

According to https://hub.docker.com/r/deeppavlov/base-gpu/tags, latest Docker image's version is 0.15.

Update Docker images, please?

Thanks!

**Comment by sumit-158** [comment]
can I work on this?

**Comment by IgnatovFedor** [comment]
Containers have updated. New [repository](https://hub.docker.com/r/deeppavlov/deeppavlov) created for images with DeepPavlov 1.0.0 and newer.

**Comment by kuraga** [comment]
Actual again.
And remove the old hubs (not images), maybe?
