### ISSUE TITLE
Добавление кастомного словаря/добавление слов в словарь по умолчанию

### ISSUE THREAD

**Issue by putassu** [deeppavlov/DeepPavlov#1527]
Из-за специфики предметных областей и обилия терминов spelling correction работает некорректно. Например на медицинских электронных документах. В словаре по умолчанию нет терминов и/или слэнговых выражений, тривиальных сокращений.
Эту проблему довольно легко решить, если позволить юзеру добавлять отсутствующие в словаре по умолчанию слова. Или добавить возможность указать ссылку на кастомный словарь в конфигурационном файле.
Как я решал эту проблему: скачал словарь по умолчанию, изменил его(добавив несколько новых слов), залил на гугл диск, изменил ссылку в конфигурационном файле на новый словарь(архив). Во время билдинга модели скачивается, но не распаковывается, а сама модель вообще перестает работать. Приложил скриншот.
![2022-02-16_18-42-23](https://user-images.githubusercontent.com/57058602/154300471-abca1fb7-1083-4ab4-91ae-7087e4a23119.png)

**Comment by Kolpnick** [comment]
@putassu, добрый день!
Мы протестировали конфиг levenshtein_corrector_ru из DeepPavlov 1.2.0, предварительно добавив новые слова в самый конец словаря по умолчанию (пример добавленной строки: `патологии\t1\n`), - и не столкнулись с проблемой билдинга модели (см. скриншот). Если у вас есть ещё замечания и предложения, будем рады ответить на них.
![image](https://github.com/deeppavlov/DeepPavlov/assets/99244955/b62ed556-f932-40e0-b2ef-b9c6f012328d)
