### ISSUE TITLE
No such file or directory: 'syntax_ru_syntagrus_bert'

### ISSUE THREAD

**Issue by KobanBanan** [deeppavlov/DeepPavlov#1619]
Hi! I am trying to install syntax_ru_syntagrus_bert form this documentation [https://docs.deeppavlov.ai/en/0.9.0/features/models/syntaxparser.html](url)
 
I followed `python -m deeppavlov install syntax_ru_syntagrus_bert`

and got an error:

`FileNotFoundError: [Errno 2] No such file or directory: 'syntax_ru_syntagrus_bert'`

` deeppavlov.__version__ == '1.0.0'`

**Python**: tried both 3.7.8 and 3.8.10

**OS**: MacOS M1

**Comment by annadmitrieva** [comment]
I have the same problem.

I found a workaround which requires the following specifications: 
```
python==3.7.1 
deeppavlov==0.17.1 
gast==0.2.2 
keras-applications==1.0.8 
tensorboard==1.15.0 
tensorflow==1.15.5 
tensorflow-estimator==1.15.1
protobuf==3.20.*
```
Then, you may face the issue with OpenSSL that can be resolved as in: https://stackoverflow.com/q/73830524 (I opted for the `rm -rf` path). 

Unfortunately, I don't know if that will work if you are in Google Colab, for instance.

**Comment by IgnatovFedor** [comment]
Hi, @KobanBanan and @annadmitrieva.
This model was removed from library, but since 1.3.0 it returned. Use deeppavlov>=1.3.0.
