### ISSUE TITLE
CRF model is not saved to correct path when training NER

### ISSUE THREAD

**Issue by landert** [deeppavlov/DeepPavlov#1625]
**DeepPavlov version**: 1.0.2
**Python version**: 3.7
**Operating system**: Ubuntu

**Issue**:
I'm training NER model from `ner_ontonotes_bert_mult` from scratch. The model is using CRF but when the training is done, the CRF model is not saved into `save_path` defined in the config. Only transformer model is saved correctly.

**Content or a name of a configuration file**:
```
https://github.com/deeppavlov/DeepPavlov/blob/1.0.2/deeppavlov/configs/ner/ner_ontonotes_bert_mult.json
```

**Command that led to error**:
```python
from deeppavlov import build_model, train_model
from deeppavlov.core.commands.utils import parse_config

model_config = parse_config('ner_ontonotes_bert_mult')
model_config['metadata']['download'] = []
ner_model = train_model(model_config)  # does not save CRF model correctly
ner_model.save()  # does not save CRF model correctly either

ner_model = build_model(ner_config, download=False)  # prints warning below
```

**Error**:
Loading model from config prints this warning.
```
WARNING in 'deeppavlov.models.torch_bert.torch_transformers_sequence_tagger'['torch_transformers_sequence_tagger'] at line 312: Init from scratch. Load path /tmp/tmpeb6cmnby/models/ner_ontonotes_torch_bert_mult_crf/model_crf.pth.tar does not exist.
```

I think the problem is in the save method [here](https://github.com/deeppavlov/DeepPavlov/blob/1.0.2/deeppavlov/models/torch_bert/torch_transformers_sequence_tagger.py#L317-L321). The parameter `fname` is `None` and therefore the CRF model is saved into file `None_crf.pth.tar` in the current working directory.
I think there should be condition like [this](https://github.com/deeppavlov/DeepPavlov/blob/1.0.2/deeppavlov/core/models/torch_model.py#L203-L204), as it is in the save method of the torch model.

**Comment by landert** [comment]
BTW results with and without CRF are pretty much the same. The CRF is probably good in combination with the original Bi-LSTM model ([here](https://arxiv.org/pdf/1709.09686.pdf)) but it has no impact on model with BERT.

These experiments came to the same conclusion:
* [NER-BERT-CRF](https://github.com/Louis-udm/NER-BERT-CRF#performance) (see section Performance)
* [NER using BERT-CRF](https://www.researchgate.net/publication/336018462_Portuguese_Named_Entity_Recognition_using_BERT-CRF) (see table 2 on page 6)

**Comment by dmitrijeuseew** [comment]
We will fix the bug in the next release.
Indeed, in some cases CRF does not have a big impact on token classification model, so you can set the flag "use_crf": false
https://github.com/deeppavlov/DeepPavlov/blob/a1e9477bf4c29b2411339d4170a67cb2fcfa667f/deeppavlov/configs/ner/ner_ontonotes_bert.json#L41

**Comment by IgnatovFedor** [comment]
#1637 fixed this issue. Will be in DeepPavlov 1.2.0.
