### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by Xtreemrus** [deeppavlov/DeepPavlov#1626]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

Please enter all the information below, otherwise your issue may be closed without a warning. 

**DeepPavlov version**  deeppavlov-1.0.2

**Python version** 3.9.9:

**Operating system**  windows:

**Issue**:
Ошибка
ModuleNotFoundError: No module named 'torch'
Конечно очевидно, что нужно просто установить torch, но для пользователя python уже становится привычным, что зависимости тянутся автоматически при pip install.

**Comment by IgnatovFedor** [comment]
Для установки зависимостей модели требуется выполнить `python -m deeppavlov install <название модели>`. Если модель используется из CLI в режиме riseapi/interact, достаточно добавить ключ `-i`. Если модель используется из python, например, с момощью deeppavlov.build_model, можно добавить аргумент `install=True`. См. [README](https://github.com/deeppavlov/DeepPavlov#command-line-interface-cli).
Учитывая, что часть моделей в библиотеке не использует torch, мы решили не включать его в базовые зависимости библиотеки.
