### ISSUE TITLE
Predictions NER_Ontonotes_BERT_Mult for entities with interpunction

### ISSUE THREAD

**Issue by ronaldvelzen** [deeppavlov/DeepPavlov#1628]
DeepPavlov version: 1.0.2
Python version: 3.8
Operating system: Ubuntu

**Issue**:
I am using the `ner_ontonotes_bert_mult` model to predict entities for text. For sentences with interpunction in the entities, this gives unexpected results. Before the 1.0.0 release, I used the [Deeppavlov docker image](https://hub.docker.com/r/deeppavlov/base-cpu) with the `ner_ontonotes_bert_mult` config as well. I didn't encounter these issues with the older version of Deeppavlov. 

**Content or a name of a configuration file**:
```
[ner_ontonotes_bert_mult](https://github.com/deeppavlov/DeepPavlov/blob/1.0.2/deeppavlov/configs/ner/ner_ontonotes_bert_mult.json)
```

**Command that led to the unexpected results**:
```python
from deeppavlov import build_model

deeppavlov_model = build_model(
        "ner_ontonotes_bert_mult",
        install=True,
        download=True)

sentence = 'Today at 13:10 we had a meeting'
output = deeppavlov_model([sentence])
print(output[0])
[['Today', 'at', '13', ':', '10', 'we', 'had', 'a', 'meeting']]
print(output[1])
[['O', 'O', 'B-TIME', 'O', 'B-TIME', 'O', 'O', 'O', 'O']]
```

As you can see `13:10` is not recognized as a time entity as a whole, but `13` as `B-TIME`, `:` as O, and `10` as `B-time`. The same happens for names with interpunctions such as `E.A. Jones`. I was wondering what I could do to solve this issue, is it possible to fine-tune this model on such examples?

**Comment by dmitrijeuseew** [comment]
The model ner_ontonotes_bert.json
https://github.com/deeppavlov/DeepPavlov/blob/master/deeppavlov/configs/ner/ner_ontonotes_bert.json
gives correct prediction for you example sentence. I suggest using English config for English sentences.
