### ISSUE TITLE
How to train goal oriented bot for my language?

### ISSUE THREAD

**Issue by lattice0** [deeppavlov/DeepPavlov#185]
Is it feasible? As I can see, the goal oriented part required, at least for english, a dataset designed specifically for it. So if I want to train it for Brazillian Portuguese I'd have to hire people to create, for example, restaurant dialogs?

Is there any work on support for other languages?

#question

**Comment by vikmary** [comment]
The library is mostly targeted on English and Russian languages.
Nevertheless, you can build [go_bot](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/go_bot/gobot_dstc2.json) on any language, if you provide:
- labeled dataset for go bot (for format specification see [go_bot](https://github.com/deepmipt/DeepPavlov/tree/master/deeppavlov/skills/go_bot))
- labeled dataset for slot filler (optional)
- labeled dataset for intent classifier (optional)
- embedder (you can still use [`deeppavlov.models.fasttext_embedder:FasttextEmbedder`](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/embedders/fasttext_embedder.py), just download model for your language from official fasttext website
- tokenizer (and change config section `tokenizer`)
- templates for your task (templates is a mapping from bot text responses to actions)
