### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JiahangOK** [deeppavlov/DeepPavlov#399]
## QUESTION:
in tutorial 04, it has bug when I learn "Interact with model using config"
## CODE:
from deeppavlov.core.commands.infer import build_model_from_config
model = build_model_from_config(config)
model(['Hi, how are you?', 'Any ideas my dear friend?'])
## BUG:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-34-fdced8328d40> in <module>()
----> 1 model(['Hi, how are you?', 'Any ideas my dear friend?'])

~/DeepPavlov/deeppavlov/core/common/chainer.py in __call__(self, *args, **kwargs)
    100 
    101     def __call__(self, *args, **kwargs):
--> 102         return self._predict(*args, **kwargs)
    103 
    104     def _predict(self, x, y=None, to_return=None):

~/DeepPavlov/deeppavlov/core/common/chainer.py in _predict(***failed resolving arguments***)
    135                 res = component(**dict(zip(in_keys, x)))
    136             else:
--> 137                 res = component(*x)
    138             if len(out_params) == 1:
    139                 mem[out_params[0]] = res

<ipython-input-10-8584ba9758e1> in __call__(self, batch, **kwargs)
     10         indices_batch = []
     11         for utt in batch:
---> 12             tokens = [self[token] for token in utt]
     13             indices_batch.append(tokens)
     14         return indices_batch

<ipython-input-10-8584ba9758e1> in <listcomp>(.0)
     10         indices_batch = []
     11         for utt in batch:
---> 12             tokens = [self[token] for token in utt]
     13             indices_batch.append(tokens)
     14         return indices_batch

~/DeepPavlov/deeppavlov/core/data/simple_vocab.py in __getitem__(self, key)
    121     def __getitem__(self, key):
    122         if isinstance(key, (int, np.integer)):
--> 123             return self._i2t[key]
    124         elif isinstance(key, str):
    125             return self._t2i[key]

IndexError: list index out of range

**Comment by yurakuratov** [comment]
Hi!
Did you change the path to dialog_vocab in config?
