### ISSUE TITLE
Lemmatizer creation and deployment with tagger

### ISSUE THREAD

**Issue by kirdin** [deeppavlov/DeepPavlov#407]
I think that the researchers who need morphological analysis in their tasks may be split up into two groups:
1) those who need only lemmatizer (for dimension reduction etc.);
2) those who need both lemmatizer and tagger.

To the best of my knowledge, there are really few applied tasks which require tagging only.

While those people who need both lemmatizer and tagger may not use your tagger due to the fact that except for your tagger they need a lemmatizer; in the mean time, all of the (good) lemmatizers for Russian (pymorphy2, mystem, rnnmorph) support tagging as well.

As a consequence, most researchers might choose another tagger due to lemmatization absence in yours.

Besides, as soon as your tagger seems to use pymorphy2 features, you could take pymorphy2 lemmas for the beginning (perhaps it is computationally easy), and then change pymorphy2 lemmatizer for your own.

**Comment by my-master** [comment]
Hi! There is already [lemmatizer for Russian](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/tokenizers/ru_tokenizer.py) language in the library, based on pymorphy2.
We will consider combining tags and lemmas in a single class soon.

**Comment by IgnatovFedor** [comment]
Closed due to the removal of the morphotagger from the library.
