### ISSUE TITLE
Complex dialogs gobot support (rules-based DM)

### ISSUE THREAD

**Issue by vitalyuf** [deeppavlov/DeepPavlov#581]
Hi!
I developed a simple skill (phone book) based on gobot. It works well.
Now I'm interested in finding out if DeepPavlov has support of rule-based dialog management (for example for complex skills).

**Comment by vikmary** [comment]
Hi
Feel free to contact me if you have any questions about `go_bot`.
We are in progress of developing a convenient way to implement dialog management rule-based components.
For now, to use rules in deeppavlov you should write python ifs.
