### ISSUE TITLE
Add ability to cache preprocessing for datasets

### ISSUE THREAD

**Issue by yoptar** [deeppavlov/DeepPavlov#600]
Running preprocessing every epoch slows SQUAD training 2x times.
This is also an issue of #569 where preprocessing is embedded in a dataset iterator

**Comment by rtygbwwwerr** [comment]
I think so, this is a solution for issue #608

**Comment by rtygbwwwerr** [comment]
I think the framework could run preprocess pipe line at first phrase, and then use data augmenter(If we have) and iterator process and feed batch data to train graph.
