### ISSUE TITLE
Logs for Tensorboard when tuning pre-trained model

### ISSUE THREAD

**Issue by dilyararimovna** [deeppavlov/DeepPavlov#767]
Hello!
It would be nice to save logs for tensorboard when training pre-trained model as a continuation of already saved logs.
Thank you!

**Comment by yoptar** [comment]
Is this issue still relevant?

**Comment by dilyararimovna** [comment]
yes

**Comment by Kolpnick** [comment]
Hello, @dilyararimovna!
In our latest release (version 1.2.0) the requested feature is present. If you think this isn’t present in the new version, let us know.
