### ISSUE TITLE
Shared components for pipes

### ISSUE THREAD

**Issue by vikmary** [deeppavlov/DeepPavlov#804]
Было бы удобно сделать возможность загрузки одной эмбеддинг-модели и использования ее для всех компонент, поскольку есть проблема потребления ресурсов: intents classifier, gobot, ner, компонент классификации навыков - все они используют одну и ту же модель, которая грузится для каждого несколько раз в память. Возможно, имеет смысл поднять эту модель в виде сервиса, к которому каждый из компонентов обращается?

**Comment by yoptar** [comment]
Same as #664
